name: Tests
on:
  pull_request:
  push:
    branches: ['master', 'n-api']

jobs:
  test:
    name: Run tests
    if: |
      !startsWith(github.event.pull_request.title, '[skip-ci]') &&
      !startsWith(github.event.pull_request.title, '[skip-package-ci]')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Python setuptools
      run: python3 -m pip install setuptools

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
